package com.github.hellagoodcoder123.enigma.typescript;

import org.enigma.typescript.intl.DateTimeFormatOptions;

public interface Date {
    String toDateString();
    String toTimeString();
    String toLocaleString();
    String toLocaleDateString();
    String toLocaleTimeString();
    long valueOf();
    long getTime();
    int getFullYear();
    int getUTCFullYear();
    int getMonth();
    int getUTCMonth();
    int getDate();
    int getUTCDate();
    int getDay();
    int getUTCDay();
    int getHours();
    int getUTCHours();
    int getMinutes();
    int getUTCMinutes();
    int getSeconds();
    int getUTCSeconds();
    int getMilliseconds();
    int getUTCMilliseconds();
    int getTimezoneOffset();
    long setTime(long time);
    int setMilliseconds(int ms);
    int setUTCMilliseconds(int ms);
    int setSeconds(int sec,int ms);
    int setSeconds(int sec);
    int setUTCSeconds(int sec,int ms);
    int setUTCSeconds(int sec);
    int setMinutes(int min,int sec,int ms);
    int setMinutes(int min,int sec);
    int setMinutes(int min);
    int setUTCMinutes(int min,int sec,int ms);
    int setUTCMinutes(int min,int sec);
    int setUTCMinutes(int min);
    int setHours(int hour,int min,int sec,int ms);
    int setHours(int hour,int min,int sec);
    int setHours(int hour,int min);
    int setHours(int hour);
    int setUTCHours(int hour,int min,int sec,int ms);
    int setUTCHours(int hour,int min,int sec);
    int setUTCHours(int hour,int min);
    int setUTCHours(int hour);
    int setDate(int date);
    int setUTCDate(int date);
    int setMonth(int month,int date);
    int setMonth(int month);
    int setUTCMonth(int month,int date);
    int setUTCMonth(int month);
    int setFullYear(int year,int month,int date);
    int setFullYear(int year,int month);
    int setFullYear(int year);
    int setUTCFullYear(int year,int month,int date);
    int setUTCFullYear(int year,int month);
    int setUTCFullYear(int year);
    String toUTCString();
    String toISOString();
    String toJSON(java.lang.Object key);
    String toJSON();
    int now();
    int UTC(int year,int month,int date,int hours,int minutes,int seconds,int ms);
    int UTC(int year,int month,int date,int hours,int minutes,int seconds);
    int UTC(int year,int month,int date,int hours,int minutes);
    int UTC(int year,int month,int date,int hours);
    int UTC(int year,int month,int date);
    int UTC(int year,int month);
    int parse(String s);
    String toLocaleString(String locales,DateTimeFormatOptions options);
    String toLocaleString(String[] locales,DateTimeFormatOptions options);
    String toLocaleString(DateTimeFormatOptions options);
    String toLocaleString(String locales);
    String toLocaleString(String[] locales);
    String toLocaleDateString(String locales,DateTimeFormatOptions options);
    String toLocaleDateString(String[] locales,DateTimeFormatOptions options);
    String toLocaleDateString(DateTimeFormatOptions options);
    String toLocaleTimeString(String locales);
    String toLocaleTimeString(String[] locales);
}