package com.github.hellagoodcoder123.enigma.typescript;

import org.enigma.function.*;

public interface Int32Array {
    public int BYTES_PER_ELEMENT=0;
    public ArrayBuffer buffer=null;
    public int byteLength=0;
    public int byteOffset=0;
    public Int32Array copyWithin(int target,int start,int end);
    public Int32Array copyWithin(int target,int start);
    public boolean every(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Object> predicate,java.lang.Object thisArg);
    public boolean every(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Object> predicate);
    public Int32Array fill(int value,int start,int end);
    public Int32Array fill(int value,int start);
    public Int32Array fill(int value);
    public Int32Array filter(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Object> predicate,java.lang.Object thisArg);
    public Int32Array filter(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Object> predicate);
    public int find(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Boolean> predicate,java.lang.Object thisArg);
    public int find(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Boolean> predicate);
    public int findIndex(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Boolean> predicate,java.lang.Object thisArg);
    public int findIndex(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Boolean> predicate);
    public void forEach(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Void> callbackfn,java.lang.Object thisArg);
    public void forEach(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Void> callbackfn);
    public int indexOf(int searchElement,int fromIndex);
    public int indexOf(int searchElement);
    public java.lang.String join(java.lang.String separator);
    public java.lang.String join();
    public int lastIndexOf(int searchElement,int fromIndex);
    public int lastIndexOf(int searchElement);
    public int length=0;
    public Int32Array map(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Number> callbackfn,java.lang.Object thisArg);
    public Int32Array map(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Number> callbackfn);
    public int reduce(QuadFunction<java.lang.Number,java.lang.Number,java.lang.Number,Int32Array,java.lang.Number> callbackfn);
    public int reduce(QuadFunction<java.lang.Number,java.lang.Number,java.lang.Number,Int32Array,java.lang.Number> callbackfn,int initialValue);
    public int reduceRight(QuadFunction<java.lang.Number,java.lang.Number,java.lang.Number,Int32Array,java.lang.Number> callbackfn);
    public int reduceRight(QuadFunction<java.lang.Number,java.lang.Number,java.lang.Number,Int32Array,java.lang.Number> callbackfn,int initialValue);
    public Int32Array reverse();
    public void set(ArrayLike<java.lang.Number> array,int offset);
    public void set(ArrayLike<java.lang.Number> array);
    public Int32Array slice(int start,int end);
    public Int32Array slice(int start);
    public Int32Array slice();
    public boolean some(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Object> predicate,java.lang.Object thisArg);
    public boolean some(TripleFunction<java.lang.Number,java.lang.Number,Int32Array,java.lang.Object> predicate);
    public Int32Array sort(java.util.function.BiFunction<java.lang.Number,java.lang.Number,java.lang.Number> compareFn);
    public Int32Array subarray(int begin,int end);
    public Int32Array subarray(int begin);
    public Int32Array subarray();
    public java.lang.String toLocaleString();
    public java.lang.String toString();
    public Int32Array valueOf();
}