package com.github.hellagoodcoder123.enigma.typescript;

public interface Math {
    int clz32(int x);
    int imul(int x,int y);
    int sign(int x);
    double log10(double x);
    double log10(float x);
    double log10(int x);
    double log2(double x);
    double log2(float x);
    double log2(int x);
    double log1p(double x);
    double log1p(float x);
    double log1p(int x);
    double expm1(double x);
    double expm1(float x);
    double expm1(int x);
    double cosh(double x);
    double cosh(float x);
    double cosh(int x);
    double sinh(double x);
    double sinh(float x);
    double sinh(int x);
    double tanh(double x);
    double tanh(float x);
    double tanh(int x);
    double acosh(double x);
    double acosh(float x);
    double acosh(int x);
    double asinh(double x);
    double asinh(float x);
    double asinh(int x);
    double atanh(double x);
    double atanh(float x);
    double atanh(int x);
    double hypot(int... values);
    double hypot(float... values);
    double hypot(double... values);
    int trunc(double x);
    int trunc(float x);
    double fround(float x);
    double fround(double x);
    int fround(int x);
    double cbrt(int x);
    double cbrt(float x);
    double cbrt(double x);
    double E=2.7182818284590452354;
    double PI=3.14159265358979323846;
    double LN2=0.6931471805599453;
    double LN10=2.302585092994046;
    double LOG2E=1.4426950408889634;
    double LOG10E=0.4342944819032518;
    double SQRT1_2=0.7071067811865476;
    double SQRT2=1.4142135623730951;
    int abs(int x);
    double abs(double x);
    float abs(float x);
    double acos(int x);
    double acos(float x);
    double acos(double x);
    double asin(int x);
    double asin(float x);
    double asin(double x);
    double atan(int x);
    double atan(float x);
    double atan(double x);
    double atan2(double y,double x);
    double atan2(double y,int x);
    double atan2(double y,float x);
    double atan2(float y,double x);
    double atan2(float y,int x);
    double atan2(float y,float x);
    double atan2(int y,double x);
    double atan2(int y,float x);
    double atan2(int y,int x);
    int ceil(int x);
    int ceil(float x);
    int ceil(double x);
    double cos(int x);
    double cos(float x);
    double cos(double x);
    double exp(int x);
    double exp(float x);
    double exp(double x);
    int floor(int x);
    int floor(float x);
    int floor(double x);
    double log(double x);
    double log(float x);
    double log(int x);
    int max(int... values);
    float max(float... values);
    double max(double... values);
    long max(long... values);
    int min(int... values);
    float min(float... values);
    double min(double... values);
    long min(long... values);
    int pow(int x,int y);
    double pow(float x,float y);
    double pow(float x,double y);
    double pow(float x,int y);
    double pow(double x,float y);
    double pow(double x,double y);
    double pow(double x,int y);
    double pow(int x,float y);
    double pow(int x,double y);
    double random();
    int round(float x);
    int round(double x);
    double sin(int x);
    double sin(float x);
    double sin(double x);
    double sqrt(int x);
    double sqrt(double x);
    double sqrt(float x);
    double tan(int x);
    double tan(float x);
    double tan(double x);
}